const SB = window.supabase.createClient(window.CC_SUPABASE_URL, window.CC_SUPABASE_KEY);
let db={services:[],appointments:[],blocks:[],staffBlocks:[],staff:[],staffServices:[],galleryCategories:[],galleryItems:[],clients:[],businessHours:[],settings:{address:'Endereço a configurar',phone:'WhatsApp a configurar',instagram:'@claudetecoiffeur',interval:30}};
let bookingState={};
const $=id=>document.getElementById(id);
const esc=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const statusLabel=s=>({pending:'Pendente',confirmed:'Confirmado',completed:'Concluído',cancelled:'Cancelado'}[s]||s);
const statusDb=s=>({Pendente:'pending',Confirmado:'confirmed',Concluído:'completed',Cancelado:'cancelled'}[s]||s);
const days=['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'];
function priceText(s){if(s.price==null)return 'Sob consulta';return `${s.price_from?'A partir de ':''}R$ ${Number(s.price).toFixed(2).replace('.',',')}`}
function serviceMap(s){return {...s,active:s.active,cat:s.category,duration:s.duration_minutes,priceText:priceText(s)}}
function galleryMap(x){return {...x,img:x.image_url,cat:x.category,desc:x.description,active:x.active}}
function appMap(a){return {...a,name:a.customer_name,service:a.service_name,staffName:a.staff_name||'—',start:a.start_at,end:a.end_at,clientType:a.client_type,status:statusLabel(a.status)}}
function blockMap(b){return {...b,start:b.start_at,end:b.end_at}}
function staffForService(serviceId){const ids=db.staffServices.filter(x=>x.service_id===serviceId).map(x=>x.staff_id);return db.staff.filter(x=>x.active&&ids.includes(x.id)).sort((a,b)=>(a.display_order||0)-(b.display_order||0)||a.name.localeCompare(b.name))}
function avatarHTML(x,cls='staffAvatar'){return x.image_url?`<img class="${cls}" src="${esc(x.image_url)}" alt="${esc(x.name)}">`:`<div class="${cls} placeholder">${esc((x.name||'?').slice(0,1).toUpperCase())}</div>`}

async function loadPublic(){
 const [sv,gc,gi,set,bh,st,ss]=await Promise.all([
  SB.from('services').select('*').eq('active',true).order('name'),
  SB.from('gallery_categories').select('*').eq('active',true).order('display_order'),
  SB.from('gallery_items').select('*').eq('active',true).order('display_order'),
  SB.from('settings').select('*').limit(1).maybeSingle(),
  SB.from('business_hours').select('*').order('day_of_week'),
  SB.from('staff').select('*').eq('active',true).order('display_order'),
  SB.from('staff_services').select('*')
 ]);
 if(sv.data)db.services=sv.data.map(serviceMap);if(gc.data)db.galleryCategories=gc.data;if(gi.data)db.galleryItems=gi.data.map(galleryMap);if(bh.data)db.businessHours=bh.data;if(st.data)db.staff=st.data;if(ss.data)db.staffServices=ss.data;
 if(set.data)db.settings={...db.settings,address:set.data.address||db.settings.address,phone:set.data.whatsapp||db.settings.phone,instagram:set.data.instagram||db.settings.instagram,interval:set.data.appointment_interval_minutes||30};
 renderPublic();
}
function renderPublic(){
 $('servicesGrid').innerHTML=db.services.filter(s=>s.active&&s.category!=='Avaliação').map(s=>`<div class=card><span class=tag>${esc(s.cat||'')}</span><h3>${esc(s.name)}</h3><p>${s.duration} min</p><div class=price>${esc(s.priceText)}</div></div>`).join('')||'<div class=card><p>Nenhum serviço cadastrado.</p></div>';
 $('gallerySections').innerHTML=db.galleryCategories.filter(c=>c.active).map((c,i)=>{const items=db.galleryItems.filter(x=>x.gallery_category_id===c.id&&x.active!==false);return `<section class="section ${i%2?'':'altbg'}"><div class=wrap><div class=eyebrow>PORTFÓLIO</div><h2>${esc(c.name)}</h2>${c.description?`<p class=muted>${esc(c.description)}</p>`:''}<div class="grid gallery">${galleryHTML(items,'Nenhuma imagem cadastrada ainda.')}</div></div></section>`}).join('')||'<section class="section altbg"><div class=wrap><h2>Portfólio</h2><p>Nenhuma categoria de galeria cadastrada.</p></div></section>';
 $('address').textContent=db.settings.address;$('hours').textContent=hoursSummary();$('phone').textContent='WhatsApp: '+db.settings.phone;$('instagram').textContent='Instagram: '+db.settings.instagram;
}
function galleryHTML(a,empty){return a.length?a.map(x=>`<div class=card><img src="${esc(x.img)}"><div class=meta><h3>${esc(x.title)}</h3><p>${esc(x.desc||'')}</p></div></div>`).join(''):`<div class=card><p>${empty}</p></div>`}
function hoursSummary(){const open=db.businessHours.filter(x=>x.is_open);if(!open.length)return 'Horários a configurar';const first=open[0];return `Funcionamento configurado • ${String(first.opening_time||'').slice(0,5)} às ${String(first.closing_time||'').slice(0,5)}`}
function galleryHTML(a,empty){return a.length?a.filter(x=>x.active!==false).map(x=>`<div class=card><img src="${esc(x.img)}"><div class=meta><span class=tag>${esc(x.cat||'')}</span><h3>${esc(x.title)}</h3><p>${esc(x.desc||'')}</p></div></div>`).join(''):`<div class=card><p>${empty}</p></div>`}

function openBooking(){const now=new Date();$('date').min=new Date(now.getTime()-now.getTimezoneOffset()*60000).toISOString().slice(0,10);$('booking').classList.add('open');resetBook()}
function closeBooking(){$('booking').classList.remove('open')}
function resetBook(){bookingState={};['s1','s2','s3','s4','s5','success'].forEach((x,i)=>$(x).classList.toggle('hidden',i!==0));$('prog').style.width='20%';$('bookMsg').innerHTML='';$('dateArea')?.classList.add('hidden')}
function step(n){['s1','s2','s3','s4','s5'].forEach((x,i)=>$(x).classList.toggle('hidden',i!==n-1));$('prog').style.width=(n*20)+'%'}
function evalService(){return db.services.find(s=>s.category==='Avaliação'||s.name.toLowerCase().includes('avaliação'))}
function chooseType(t){bookingState.type=t;step(2);$('newInfo').classList.toggle('hidden',t!=='new');if(t==='new'){const e=evalService();if(!e){$('bookMsg').innerHTML='<div class="notice error">O serviço de avaliação não foi encontrado. Cadastre-o no painel.</div>';return}$('serviceSelect').innerHTML=`<option value="${e.id}">${esc(e.name)}</option>`;$('serviceSelect').disabled=true}else{$('serviceSelect').disabled=false;$('serviceSelect').innerHTML=db.services.filter(s=>s.active&&s.category!=='Avaliação').map(s=>`<option value="${s.id}">${esc(s.name)} — ${s.duration} min</option>`).join('')}}
function goDate(){bookingState.service=$('serviceSelect').value;if(!bookingState.service)return;$('bookMsg').innerHTML='';bookingState.staff=null;step(3);renderStaffChoices()}
function renderStaffChoices(){const list=staffForService(bookingState.service),el=$('staffChoices');$('dateArea').classList.add('hidden');$('slots').innerHTML='';if(!list.length){el.innerHTML='<div class="notice error">Nenhuma atendente ativa está vinculada a este serviço. Avise o salão.</div>';return}el.innerHTML=list.map(x=>`<button class="staffPick" onclick="chooseStaff('${x.id}',this)">${avatarHTML(x)}<span><b>${esc(x.name)}</b><br><small>${esc(x.role||'Atendente')}</small><br><span class="badgeOk">Selecionar</span></span></button>`).join('')}
function chooseStaff(id,btn){bookingState.staff=id;bookingState.staffName=db.staff.find(x=>x.id===id)?.name||'';document.querySelectorAll('.staffPick').forEach(x=>x.classList.remove('selected'));btn?.classList.add('selected');$('dateArea').classList.remove('hidden');$('date').value='';$('slots').innerHTML='<p class="muted">Escolha uma data para ver os horários desta atendente.</p>'}
function mins(t){let[a,b]=String(t||'00:00').slice(0,5).split(':').map(Number);return a*60+b}function fmt(m){return String(Math.floor(m/60)).padStart(2,'0')+':'+String(m%60).padStart(2,'0')}
async function renderSlots(){const el=$('slots'),d=$('date').value;el.innerHTML='<p>Carregando horários...</p>';if(!d||!bookingState.staff)return;const sv=db.services.find(s=>s.id===bookingState.service);if(!sv)return;const day=new Date(d+'T12:00:00').getDay(),cfg=db.businessHours.find(x=>x.day_of_week===day);if(!cfg||!cfg.is_open){el.innerHTML='<div class="notice error">Salão fechado neste dia.</div>';return}
 const start=mins(cfg.opening_time),end=mins(cfg.closing_time),interval=Number(db.settings.interval||30),candidates=[];
 for(let m=start;m+sv.duration<=end;m+=interval){const st=new Date(`${d}T${fmt(m)}:00`),en=new Date(st.getTime()+sv.duration*60000);if(st<=new Date())continue;if(cfg.break_start&&cfg.break_end&&m<mins(cfg.break_end)&&m+sv.duration>mins(cfg.break_start))continue;candidates.push({m,st,en})}
 const checks=await Promise.all(candidates.map(async c=>{const {data,error}=await SB.rpc('is_staff_slot_available',{p_staff_id:bookingState.staff,p_service_id:bookingState.service,p_start_at:c.st.toISOString(),p_end_at:c.en.toISOString()});return {...c,ok:!error&&data===true}}));
 el.innerHTML='';checks.forEach(c=>{let b=document.createElement('button');b.className='choice';if(c.ok){b.innerHTML=`<b>${fmt(c.m)}</b><br><span class="badgeOk">Disponível</span>`;b.onclick=()=>{bookingState.date=d;bookingState.time=fmt(c.m);bookingState.start=c.st.toISOString();bookingState.end=c.en.toISOString();step(4)}}else{b.disabled=true;b.style.opacity='.55';b.style.cursor='not-allowed';b.innerHTML=`<b>${fmt(c.m)}</b><br><span class="badgeBusy">Atendente ocupada</span>`}el.appendChild(b)});if(!el.children.length)el.innerHTML='<div class="notice error">Sem horários nesta data.</div>'}
function review(){let n=$('name').value.trim(),w=$('whats').value.trim();$('bookMsg').innerHTML='';if(!n||!w||!$('policy').checked){$('bookMsg').innerHTML='<div class="notice error">Preencha nome, WhatsApp e aceite a política.</div>';return}if($('email').value.trim()&&!$('email').checkValidity()){$('bookMsg').innerHTML='<div class="notice error">Digite um e-mail válido ou deixe vazio.</div>';return}bookingState.name=n;bookingState.whats=w;bookingState.email=$('email').value.trim();bookingState.notes=$('notes').value.trim();let sv=db.services.find(s=>s.id===bookingState.service);if(!sv)return;step(5);$('reviewBox').innerHTML=`<b>${esc(n)}</b><br>${esc(sv.name)}<br>Atendente: ${esc(bookingState.staffName)}<br>${bookingState.date.split('-').reverse().join('/')} às ${bookingState.time}<br>Status: Pendente`}
async function submitBooking(){const btn=$('sendBtn'),sv=db.services.find(s=>s.id===bookingState.service);if(!sv)return;btn.disabled=true;$('bookMsg').innerHTML='';const payload={client_type:bookingState.type==='new'?'new':'returning',service_id:sv.id,staff_id:bookingState.staff,staff_name:bookingState.staffName,customer_name:bookingState.name,phone:bookingState.whats,email:bookingState.email||null,service_name:sv.name,start_at:bookingState.start,end_at:bookingState.end,status:'pending',notes:bookingState.notes||null,policy_accepted:true};const {error}=await SB.from('appointments').insert(payload);if(error){btn.disabled=false;const conflict=error.code==='23P01';$('bookMsg').innerHTML=`<div class="notice error">${conflict?'Ops! Essa atendente acabou de ficar ocupada nesse horário. Escolha outro horário.':'Não foi possível solicitar: '+esc(error.message)}</div>`;if(conflict){step(3);renderSlots()}return}['s1','s2','s3','s4','s5'].forEach(x=>$(x).classList.add('hidden'));$('success').classList.remove('hidden');$('successBox').innerHTML=`<b>${esc(bookingState.name)}</b><br>${esc(sv.name)}<br>Atendente: ${esc(bookingState.staffName)}<br>${bookingState.date.split('-').reverse().join('/')} às ${bookingState.time}<br>Status: Pendente<br><br><button class="btn" onclick="sendBookingWhatsApp()">ENVIAR AGENDAMENTO PELO WHATSAPP</button>`;btn.disabled=false}
function openWhats(){const n=String(db.settings.phone||'').replace(/\D/g,'');if(n.length>=10)window.open(`https://wa.me/${n}`,'_blank');else alert('Configure o WhatsApp no painel administrativo.')}
function sendBookingWhatsApp(){const n=String(db.settings.phone||'').replace(/\D/g,'');if(n.length<10)return alert('O WhatsApp do salão ainda não foi configurado.');const sv=db.services.find(s=>s.id===bookingState.service);const msg=`Olá, Claudete! Acabei de fazer um agendamento pelo site.\n\n👤 Nome: ${bookingState.name}\n✂️ Serviço: ${sv?.name||''}\n👩 Atendente: ${bookingState.staffName}\n📅 Data: ${bookingState.date.split('-').reverse().join('/')}\n🕐 Horário: ${bookingState.time}\n📋 Status: Pendente\n\nGostaria de confirmar meu agendamento.`;window.open(`https://wa.me/${n}?text=${encodeURIComponent(msg)}`,'_blank')}

async function openAdmin(){$('admin').classList.add('open');const {data}=await SB.auth.getSession();if(data.session&&await currentIsAdmin()){$('loginView').classList.add('hidden');$('dashView').classList.remove('hidden');await loadAdmin();showTab('dash')}else{$('loginView').classList.remove('hidden');$('dashView').classList.add('hidden')}}
function closeAdmin(){$('admin').classList.remove('open')}
async function currentIsAdmin(){const {data,error}=await SB.from('admin_users').select('id').limit(1);return !error&&data&&data.length>0}
async function loginAdmin(){const email=$('adminUser').value.trim(),password=$('adminPass').value;const {error}=await SB.auth.signInWithPassword({email,password});if(error)return alert('E-mail ou senha incorretos.');if(!await currentIsAdmin()){await SB.auth.signOut();return alert('Essa conta não possui permissão de administradora.')}$('loginView').classList.add('hidden');$('dashView').classList.remove('hidden');await loadAdmin();showTab('dash')}
async function logoutAdmin(){await SB.auth.signOut();$('dashView').classList.add('hidden');$('loginView').classList.remove('hidden')}
async function loadAdmin(){const [a,b,s,c,gc,gi,set,bh,st,ss,sb]=await Promise.all([SB.from('appointments').select('*').order('start_at'),SB.from('blocked_periods').select('*').order('start_at'),SB.from('services').select('*').order('name'),SB.from('clients').select('*').order('name'),SB.from('gallery_categories').select('*').order('display_order'),SB.from('gallery_items').select('*').order('display_order'),SB.from('settings').select('*').limit(1).maybeSingle(),SB.from('business_hours').select('*').order('day_of_week'),SB.from('staff').select('*').order('display_order'),SB.from('staff_services').select('*'),SB.from('staff_blocks').select('*').order('start_at')]);if(a.data)db.appointments=a.data.map(appMap);if(b.data)db.blocks=b.data.map(blockMap);if(s.data)db.services=s.data.map(serviceMap);db.clients=c.data||[];if(gc.data)db.galleryCategories=gc.data;if(gi.data)db.galleryItems=gi.data.map(galleryMap);if(bh.data)db.businessHours=bh.data;if(st.data)db.staff=st.data;if(ss.data)db.staffServices=ss.data;if(sb.data)db.staffBlocks=sb.data.map(blockMap);if(set.data)db.settings={...db.settings,address:set.data.address||'',phone:set.data.whatsapp||'',instagram:set.data.instagram||'',interval:set.data.appointment_interval_minutes||30,settingsId:set.data.id};renderPublic()}
function showTab(t){({dash:renderDash,apps:renderApps,services:renderServices,staff:renderStaff,hours:renderHours,blocks:renderBlocks,gallery:renderGallery,settings:renderSettings}[t])()}
function renderDash(){let today=new Date().toISOString().slice(0,10),aps=db.appointments;$('adminContent').innerHTML=`<h2>Dashboard</h2><div class=stats><div class=stat><b>${aps.filter(a=>a.start.slice(0,10)==today).length}</b>Hoje</div><div class=stat><b>${aps.filter(a=>a.status==='Pendente').length}</b>Pendentes</div><div class=stat><b>${aps.filter(a=>a.status==='Confirmado').length}</b>Confirmados</div><div class=stat><b>${db.staff.filter(x=>x.active).length}</b>Atendentes</div></div><h3>Próximos agendamentos</h3>${appsTable(aps.filter(a=>new Date(a.start)>=new Date()).slice(0,8))}`}
function appsTable(a){return `<div style="overflow:auto"><table class=table><tr><th>Cliente</th><th>Serviço</th><th>Atendente</th><th>Data</th><th>Status</th><th>Ações</th></tr>${a.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.service)}</td><td>${esc(x.staffName)}</td><td>${new Date(x.start).toLocaleString('pt-BR')}</td><td>${x.status}</td><td><button class=tiny onclick="statusApp('${x.id}','Confirmado')">✓</button> <button class=tiny onclick="statusApp('${x.id}','Concluído')">Fim</button> <button class=tiny onclick="statusApp('${x.id}','Cancelado')">×</button></td></tr>`).join('')}</table></div>`}
function renderApps(){$('adminContent').innerHTML='<h2>Agendamentos</h2>'+appsTable(db.appointments)}
async function statusApp(id,s){const {error}=await SB.from('appointments').update({status:statusDb(s)}).eq('id',id);if(error)return alert(error.message);await loadAdmin();renderApps()}

function renderServices(){$('adminContent').innerHTML=`<h2>Serviços</h2><div class=card><div class=row><input id=sn placeholder="Nome"><input id=sc placeholder="Categoria"></div><div class=row><input id=sd type=number placeholder="Duração em minutos"><input id=sp type=number step=.01 placeholder="Preço"></div><label><input id=spf type=checkbox style="width:auto"> Preço "A partir de"</label><button class=btn onclick=addService()>Adicionar</button></div><div class=grid>${db.services.map(s=>`<div class=card><b>${esc(s.name)}</b><p>${s.duration} min • ${esc(s.priceText)}</p><button class=tiny onclick="toggleService('${s.id}',${!s.active})">${s.active?'Desativar':'Ativar'}</button> <button class=tiny onclick="delService('${s.id}')">Excluir</button></div>`).join('')}</div>`}
async function addService(){if(!$('sn').value||!$('sd').value)return;const {error}=await SB.from('services').insert({name:$('sn').value,category:$('sc').value||'Outros',duration_minutes:+$('sd').value,price:$('sp').value?+$('sp').value:null,price_from:$('spf').checked,active:true});if(error)return alert(error.message);await loadAdmin();renderServices()}
async function toggleService(id,v){const {error}=await SB.from('services').update({active:v}).eq('id',id);if(error)return alert(error.message);await loadAdmin();renderServices()}
async function delService(id){if(!confirm('Excluir este serviço?'))return;const {error}=await SB.from('services').delete().eq('id',id);if(error)return alert(error.message);await loadAdmin();renderServices()}

function serviceChecks(selected=[]){return `<div class="serviceChecks">${db.services.filter(s=>s.active).map(s=>`<label><input type="checkbox" class="staffSvc" value="${s.id}" ${selected.includes(s.id)?'checked':''} style="width:auto"> ${esc(s.name)}</label>`).join('')}</div>`}
function renderStaff(){const cards=db.staff.map(x=>{const svcs=db.staffServices.filter(y=>y.staff_id===x.id).map(y=>db.services.find(s=>s.id===y.service_id)?.name).filter(Boolean);return `<div class=card><div class=staffAdmin>${avatarHTML(x)}<div><h3>${esc(x.name)}</h3><p>${esc(x.role||'Atendente')}</p><p class=muted>${esc(svcs.join(' • ')||'Nenhum serviço vinculado')}</p><span class="${x.active?'badgeOk':'badgeBusy'}">${x.active?'Ativa':'Desativada'}</span><p><button class=tiny onclick="editStaff('${x.id}')">Editar</button> <button class=tiny onclick="toggleStaff('${x.id}',${!x.active})">${x.active?'Desativar':'Ativar'}</button> <button class="tiny dangerBtn" onclick="deleteStaff('${x.id}')">Excluir</button></p></div></div></div>`}).join('');$('adminContent').innerHTML=`<h2>Atendentes</h2><p class=muted>Cadastre profissionais, foto e os serviços que cada uma realiza. Uma mesma profissional pode ter vários serviços.</p><div class=card><input type=hidden id=staffId><div class=row><div><label>Nome</label><input id=staffName placeholder="Nome da atendente"></div><div><label>Função / especialidade</label><input id=staffRole placeholder="Ex.: Cabeleireira"></div></div><label>Foto</label><input id=staffFile type=file accept="image/*"><label>Serviços realizados</label><div id=staffSvcBox>${serviceChecks()}</div><label><input id=staffActive type=checkbox checked style="width:auto"> Atendente ativa</label><button class=btn onclick=saveStaff()>SALVAR ATENDENTE</button> <button class="btn alt" onclick=clearStaffForm()>LIMPAR</button></div><div class=grid>${cards||'<div class=card>Nenhuma atendente cadastrada.</div>'}</div>`}
function clearStaffForm(){renderStaff()}
function editStaff(id){const x=db.staff.find(s=>s.id===id);if(!x)return;$('staffId').value=x.id;$('staffName').value=x.name;$('staffRole').value=x.role||'';$('staffActive').checked=x.active;const selected=db.staffServices.filter(y=>y.staff_id===id).map(y=>y.service_id);$('staffSvcBox').innerHTML=serviceChecks(selected);window.scrollTo({top:0,behavior:'smooth'})}
async function uploadStaffPhoto(file,id){if(!file)return null;const ext=(file.name.split('.').pop()||'jpg').replace(/[^a-zA-Z0-9]/g,'');const path=`staff/${id}-${Date.now()}.${ext}`;const up=await SB.storage.from('gallery').upload(path,file,{upsert:false});if(up.error)throw up.error;return SB.storage.from('gallery').getPublicUrl(path).data.publicUrl}
async function saveStaff(){const id=$('staffId').value,name=$('staffName').value.trim(),role=$('staffRole').value.trim(),file=$('staffFile').files[0],active=$('staffActive').checked,services=[...document.querySelectorAll('.staffSvc:checked')].map(x=>x.value);if(!name)return alert('Informe o nome da atendente.');if(!services.length)return alert('Marque pelo menos um serviço.');let staffId=id;try{if(!staffId){const {data,error}=await SB.from('staff').insert({name,role:role||null,active}).select('id').single();if(error)throw error;staffId=data.id}else{const {error}=await SB.from('staff').update({name,role:role||null,active}).eq('id',staffId);if(error)throw error}if(file){const image_url=await uploadStaffPhoto(file,staffId);const {error}=await SB.from('staff').update({image_url}).eq('id',staffId);if(error)throw error}let del=await SB.from('staff_services').delete().eq('staff_id',staffId);if(del.error)throw del.error;let ins=await SB.from('staff_services').insert(services.map(service_id=>({staff_id:staffId,service_id})));if(ins.error)throw ins.error;await loadAdmin();renderStaff();alert('Atendente salva com sucesso.')}catch(e){alert(e.message||'Não foi possível salvar a atendente.')}}
async function toggleStaff(id,v){const {error}=await SB.from('staff').update({active:v}).eq('id',id);if(error)return alert(error.message);await loadAdmin();renderStaff()}
async function deleteStaff(id){if(!confirm('Excluir esta atendente? Se ela tiver agendamentos antigos, prefira Desativar.'))return;const {error}=await SB.from('staff').delete().eq('id',id);if(error)return alert('Não foi possível excluir. Se ela já possui agendamentos, use Desativar.');await loadAdmin();renderStaff()}

function renderHours(){$('adminContent').innerHTML=`<h2>Horários de funcionamento</h2><p class=muted>Altere os dias e horários do salão. O site passa a usar estes valores nos próximos agendamentos.</p><div class=card>${db.businessHours.map(x=>`<div class=hoursRow data-day="${x.day_of_week}"><div><b>${days[x.day_of_week]}</b></div><label><input class=hopen type=checkbox ${x.is_open?'checked':''} style="width:auto"> Aberto</label><label>Abre<input class=hop type=time value="${String(x.opening_time||'09:00').slice(0,5)}"></label><label>Fecha<input class=hcl type=time value="${String(x.closing_time||'18:00').slice(0,5)}"></label><label>Início pausa<input class=hbs type=time value="${String(x.break_start||'').slice(0,5)}"></label><label>Fim pausa<input class=hbe type=time value="${String(x.break_end||'').slice(0,5)}"></label></div>`).join('')}<button class=btn onclick=saveHours()>SALVAR HORÁRIOS</button></div>`}
async function saveHours(){const rows=[...document.querySelectorAll('.hoursRow')];for(const r of rows){const day=+r.dataset.day,payload={is_open:r.querySelector('.hopen').checked,opening_time:r.querySelector('.hop').value||null,closing_time:r.querySelector('.hcl').value||null,break_start:r.querySelector('.hbs').value||null,break_end:r.querySelector('.hbe').value||null};const {error}=await SB.from('business_hours').update(payload).eq('day_of_week',day);if(error)return alert(error.message)}await loadAdmin();renderHours();alert('Horários atualizados.')}

function renderBlocks(){const all=[...db.blocks.map(b=>({...b,kind:'Salão inteiro',staff_id:null})),...db.staffBlocks.map(b=>({...b,kind:db.staff.find(s=>s.id===b.staff_id)?.name||'Atendente'}))].sort((a,b)=>new Date(a.start)-new Date(b.start));$('adminContent').innerHTML=`<h2>Bloqueios</h2><div class=card><label>Quem ficará indisponível?</label><select id=blockStaff><option value="">Salão inteiro</option>${db.staff.filter(x=>x.active).map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select><div class=row><div><label>Início</label><input id=bs type=datetime-local></div><div><label>Fim</label><input id=be type=datetime-local></div></div><label>Motivo</label><input id=br placeholder="Ex.: folga / férias / compromisso"><button class=btn onclick=addBlock()>Bloquear</button></div><div class=grid>${all.map(b=>`<div class=card><span class=tag>${esc(b.kind)}</span><b style="display:block;margin-top:8px">${esc(b.reason||b.title||'Bloqueado')}</b><p>${new Date(b.start).toLocaleString('pt-BR')} → ${new Date(b.end).toLocaleString('pt-BR')}</p><button class=tiny onclick="delBlock('${b.id}',${b.staff_id?`'staff'`:`'global'`})">Excluir</button></div>`).join('')}</div>`}
async function addBlock(){if(!$('bs').value||!$('be').value)return;const staffId=$('blockStaff').value,payload={title:$('br').value||'Indisponível',start_at:new Date($('bs').value).toISOString(),end_at:new Date($('be').value).toISOString()};let res;if(staffId)res=await SB.from('staff_blocks').insert({...payload,staff_id:staffId});else res=await SB.from('blocked_periods').insert({...payload,reason:$('br').value||'Bloqueado'});if(res.error)return alert(res.error.message);await loadAdmin();renderBlocks()}
async function delBlock(id,kind='global'){const {error}=await SB.from(kind==='staff'?'staff_blocks':'blocked_periods').delete().eq('id',id);if(error)return alert(error.message);await loadAdmin();renderBlocks()}

function renderGallery(){const cats=db.galleryCategories;const catOptions=cats.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');$('adminContent').innerHTML=`<h2>Galerias</h2><p class=muted>Crie, renomeie, ative, desative ou exclua categorias sem alterar o código do site.</p><div class=card><h3>Nova categoria</h3><input type=hidden id=gcatId><div class=row><div><label>Nome</label><input id=gcatName placeholder="Ex.: Cílios"></div><div><label>Ordem</label><input id=gcatOrder type=number value=0></div></div><label>Descrição opcional</label><input id=gcatDesc placeholder="Texto que aparece no site"><label><input id=gcatActive type=checkbox checked style="width:auto"> Categoria visível no site</label><button class=btn onclick=saveGalleryCategory()>SALVAR CATEGORIA</button> <button class="btn alt" onclick=renderGallery()>LIMPAR</button></div><div class=grid>${cats.map(c=>`<div class=card><span class="${c.active?'badgeOk':'badgeBusy'}">${c.active?'Visível':'Oculta'}</span><h3>${esc(c.name)}</h3><p>${esc(c.description||'')}</p><button class=tiny onclick="editGalleryCategory('${c.id}')">Editar</button> <button class=tiny onclick="toggleGalleryCategory('${c.id}',${!c.active})">${c.active?'Ocultar':'Mostrar'}</button> <button class=tiny onclick="deleteGalleryCategory('${c.id}')">Excluir</button></div>`).join('')||'<div class=card>Nenhuma categoria.</div>'}</div><hr><div class=card><h3>Adicionar foto</h3><label>Categoria</label><select id=gt>${catOptions}</select><label>Título</label><input id=gtitle><label>Descrição</label><textarea id=gdesc></textarea><label>Imagem</label><input id=gfile type=file accept="image/*"><button class=btn onclick=addGallery()>ADICIONAR IMAGEM</button></div>${cats.map(c=>`<h3>${esc(c.name)}</h3><div class="grid gallery">${galleryAdmin(db.galleryItems.filter(x=>x.gallery_category_id===c.id))}</div>`).join('')}`}
function editGalleryCategory(id){const c=db.galleryCategories.find(x=>x.id===id);if(!c)return;$('gcatId').value=c.id;$('gcatName').value=c.name;$('gcatDesc').value=c.description||'';$('gcatOrder').value=c.display_order||0;$('gcatActive').checked=c.active}
async function saveGalleryCategory(){const id=$('gcatId').value,name=$('gcatName').value.trim();if(!name)return alert('Informe o nome da categoria.');const payload={name,description:$('gcatDesc').value.trim()||null,display_order:+$('gcatOrder').value||0,active:$('gcatActive').checked};const res=id?await SB.from('gallery_categories').update(payload).eq('id',id):await SB.from('gallery_categories').insert(payload);if(res.error)return alert(res.error.message);await loadAdmin();renderGallery()}
async function toggleGalleryCategory(id,v){const {error}=await SB.from('gallery_categories').update({active:v}).eq('id',id);if(error)return alert(error.message);await loadAdmin();renderGallery()}
async function deleteGalleryCategory(id){const count=db.galleryItems.filter(x=>x.gallery_category_id===id).length;if(count&&!confirm(`Essa categoria possui ${count} imagem(ns). Excluir a categoria também excluirá esses registros e arquivos. Continuar?`))return;if(!count&&!confirm('Excluir esta categoria?'))return;const items=db.galleryItems.filter(x=>x.gallery_category_id===id);const {error}=await SB.from('gallery_categories').delete().eq('id',id);if(error)return alert(error.message);for(const item of items)await removeGalleryStorage(item.image_url);await loadAdmin();renderGallery()}
function galleryAdmin(a){return a.map(x=>`<div class=card><img src="${esc(x.img)}"><h3>${esc(x.title)}</h3><p>${esc(x.desc||'')}</p><button class=tiny onclick="delGallery('${x.id}')">Excluir</button></div>`).join('')||'<div class=card><p>Nenhuma imagem nesta categoria.</p></div>'}
async function addGallery(){const f=$('gfile').files[0],categoryId=$('gt').value;if(!categoryId)return alert('Crie uma categoria primeiro.');if(!f||!$('gtitle').value.trim())return alert('Escolha uma imagem e informe o título.');const path=`portfolio/${categoryId}/${Date.now()}-${f.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const up=await SB.storage.from('gallery').upload(path,f,{upsert:false});if(up.error)return alert(up.error.message);const {data:urlData}=SB.storage.from('gallery').getPublicUrl(path);const {error}=await SB.from('gallery_items').insert({gallery_category_id:categoryId,title:$('gtitle').value.trim(),description:$('gdesc').value.trim()||null,image_url:urlData.publicUrl,active:true});if(error){await SB.storage.from('gallery').remove([path]);return alert(error.message)}await loadAdmin();renderGallery()}
async function removeGalleryStorage(url){if(!url)return;const marker='/storage/v1/object/public/gallery/',pos=url.indexOf(marker);if(pos>=0)await SB.storage.from('gallery').remove([decodeURIComponent(url.slice(pos+marker.length))])}
async function delGallery(id){if(!confirm('Excluir esta imagem?'))return;const item=db.galleryItems.find(x=>x.id===id);const {error}=await SB.from('gallery_items').delete().eq('id',id);if(error)return alert(error.message);await removeGalleryStorage(item?.image_url);await loadAdmin();renderGallery()}
function renderSettings(){let s=db.settings;$('adminContent').innerHTML=`<h2>Configurações</h2><div class=card><label>Endereço</label><input id=setAddr value="${esc(s.address)}"><label>WhatsApp</label><input id=setPhone value="${esc(s.phone)}"><label>Instagram</label><input id=setInsta value="${esc(s.instagram)}"><label>Intervalo entre opções (min)</label><input id=setInt type=number value="${s.interval}"><button class=btn onclick=saveSettings()>Salvar</button><p class=muted>Os horários agora podem ser alterados pela aba Horários.</p><button class="btn alt" onclick=logoutAdmin()>Sair da conta</button></div>`}
async function saveSettings(){const payload={address:$('setAddr').value,whatsapp:$('setPhone').value,instagram:$('setInsta').value,appointment_interval_minutes:+$('setInt').value};const {error}=await SB.from('settings').update(payload).eq('id',db.settings.settingsId);if(error)return alert(error.message);await loadAdmin();alert('Configurações salvas.')}

loadPublic().catch(e=>{console.error(e);$('servicesGrid').innerHTML='<div class="notice error">Não foi possível conectar ao Supabase. Confira config.js.</div>'});
