const SB = window.supabase.createClient(window.CC_SUPABASE_URL, window.CC_SUPABASE_KEY);
let db={services:[],appointments:[],blocks:[],hair:[],nails:[],businessHours:[],settings:{address:'Endereço a configurar',phone:'WhatsApp a configurar',instagram:'@claudetecoiffeur',interval:30}};
let bookingState={};
const $=id=>document.getElementById(id); const esc=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const statusLabel=s=>({pending:'Pendente',confirmed:'Confirmado',completed:'Concluído',cancelled:'Cancelado'}[s]||s);
const statusDb=s=>({Pendente:'pending',Confirmado:'confirmed',Concluído:'completed',Cancelado:'cancelled'}[s]||s);
function priceText(s){if(s.price==null)return 'Sob consulta';return `${s.price_from?'A partir de ':''}R$ ${Number(s.price).toFixed(2).replace('.',',')}`}
function serviceMap(s){return {...s,active:s.active,cat:s.category,duration:s.duration_minutes,priceText:priceText(s)}}
function galleryMap(x){return {...x,img:x.image_url,cat:x.category,desc:x.description,active:x.active}}
function appMap(a){return {...a,name:a.customer_name,service:a.service_name,start:a.start_at,end:a.end_at,clientType:a.client_type,status:statusLabel(a.status)}}
function blockMap(b){return {...b,start:b.start_at,end:b.end_at}}

async function loadPublic(){
 const [sv,hr,ng,set,bh]=await Promise.all([
  SB.from('services').select('*').eq('active',true).order('name'),
  SB.from('hair_gallery').select('*').eq('active',true).order('display_order'),
  SB.from('nail_gallery').select('*').eq('active',true).order('display_order'),
  SB.from('settings').select('*').limit(1).maybeSingle(),
  SB.from('business_hours').select('*').order('day_of_week')
 ]);
 if(sv.data)db.services=sv.data.map(serviceMap); if(hr.data)db.hair=hr.data.map(galleryMap); if(ng.data)db.nails=ng.data.map(galleryMap); if(bh.data)db.businessHours=bh.data;
 if(set.data)db.settings={...db.settings,address:set.data.address||db.settings.address,phone:set.data.whatsapp||db.settings.phone,instagram:set.data.instagram||db.settings.instagram,interval:set.data.appointment_interval_minutes||30};
 renderPublic();
}
function renderPublic(){
 $('servicesGrid').innerHTML=db.services.filter(s=>s.active&&s.category!=='Avaliação').map(s=>`<div class=card><span class=tag>${esc(s.cat||'')}</span><h3>${esc(s.name)}</h3><p>${s.duration} min</p><div class=price>${esc(s.priceText)}</div></div>`).join('')||'<div class=card><p>Nenhum serviço cadastrado.</p></div>';
 $('hairGrid').innerHTML=galleryHTML(db.hair,'Nenhuma transformação cadastrada ainda.'); $('nailGrid').innerHTML=galleryHTML(db.nails,'Nenhum design cadastrado ainda.');
 $('address').textContent=db.settings.address; $('hours').textContent='Horários configurados no sistema'; $('phone').textContent='WhatsApp: '+db.settings.phone; $('instagram').textContent='Instagram: '+db.settings.instagram;
}
function galleryHTML(a,empty){return a.length?a.filter(x=>x.active!==false).map(x=>`<div class=card><img src="${esc(x.img)}"><div class=meta><span class=tag>${esc(x.cat||'')}</span><h3>${esc(x.title)}</h3><p>${esc(x.desc||'')}</p></div></div>`).join(''):`<div class=card><p>${empty}</p></div>`}

function openBooking(){const now=new Date();$('date').min=new Date(now.getTime()-now.getTimezoneOffset()*60000).toISOString().slice(0,10);$('booking').classList.add('open');resetBook()}
function closeBooking(){$('booking').classList.remove('open')}
function resetBook(){bookingState={};['s1','s2','s3','s4','s5','success'].forEach((x,i)=>$(x).classList.toggle('hidden',i!==0));$('prog').style.width='20%';$('bookMsg').innerHTML=''}
function step(n){['s1','s2','s3','s4','s5'].forEach((x,i)=>$(x).classList.toggle('hidden',i!==n-1));$('prog').style.width=(n*20)+'%'}
function evalService(){return db.services.find(s=>s.category==='Avaliação'||s.name.toLowerCase().includes('avaliação'))}
function chooseType(t){bookingState.type=t;step(2);$('newInfo').classList.toggle('hidden',t!=='new');if(t==='new'){const e=evalService();if(!e){$('bookMsg').innerHTML='<div class="notice error">O serviço de avaliação não foi encontrado. Cadastre-o no painel.</div>';return}$('serviceSelect').innerHTML=`<option value="${e.id}">${esc(e.name)}</option>`;$('serviceSelect').disabled=true}else{$('serviceSelect').disabled=false;$('serviceSelect').innerHTML=db.services.filter(s=>s.active&&s.category!=='Avaliação').map(s=>`<option value="${s.id}">${esc(s.name)} — ${s.duration} min</option>`).join('')}}
function goDate(){bookingState.service=$('serviceSelect').value;if(!bookingState.service)return;$('bookMsg').innerHTML='';step(3);renderSlots()}
function mins(t){let[a,b]=t.slice(0,5).split(':').map(Number);return a*60+b} function fmt(m){return String(Math.floor(m/60)).padStart(2,'0')+':'+String(m%60).padStart(2,'0')}
async function renderSlots(){const el=$('slots'),d=$('date').value;el.innerHTML='<p>Carregando horários...</p>';if(!d)return;const sv=db.services.find(s=>s.id===bookingState.service);if(!sv)return;const day=new Date(d+'T12:00:00').getDay(),cfg=db.businessHours.find(x=>x.day_of_week===day);if(!cfg||!cfg.is_open){el.innerHTML='<div class="notice error">Salão fechado neste dia.</div>';return}
 const start=mins(cfg.opening_time),end=mins(cfg.closing_time),interval=Number(db.settings.interval||30),candidates=[];
 for(let m=start;m+sv.duration<=end;m+=interval){const st=new Date(`${d}T${fmt(m)}:00`),en=new Date(st.getTime()+sv.duration*60000);if(st<=new Date())continue;if(cfg.break_start&&cfg.break_end&&m<mins(cfg.break_end)&&m+sv.duration>mins(cfg.break_start))continue;candidates.push({m,st,en})}
 const checks=await Promise.all(candidates.map(async c=>{const {data,error}=await SB.rpc('is_slot_available',{p_start_at:c.st.toISOString(),p_end_at:c.en.toISOString()});return {...c,ok:!error&&data===true}}));el.innerHTML='';checks.filter(c=>c.ok).forEach(c=>{let b=document.createElement('button');b.className='choice';b.textContent=fmt(c.m);b.onclick=()=>{bookingState.date=d;bookingState.time=fmt(c.m);bookingState.start=c.st.toISOString();bookingState.end=c.en.toISOString();step(4)};el.appendChild(b)});if(!el.children.length)el.innerHTML='<div class="notice error">Sem horários disponíveis para esta data.</div>'}
function review(){let n=$('name').value.trim(),w=$('whats').value.trim();$('bookMsg').innerHTML='';if(!n||!w||!$('policy').checked){$('bookMsg').innerHTML='<div class="notice error">Preencha nome, WhatsApp e aceite a política.</div>';return}if($('email').value.trim()&&!$('email').checkValidity()){$('bookMsg').innerHTML='<div class="notice error">Digite um e-mail válido ou deixe vazio.</div>';return}bookingState.name=n;bookingState.whats=w;bookingState.email=$('email').value.trim();bookingState.notes=$('notes').value.trim();let sv=db.services.find(s=>s.id===bookingState.service);if(!sv)return;step(5);$('reviewBox').innerHTML=`<b>${esc(n)}</b><br>${esc(sv.name)}<br>${bookingState.date.split('-').reverse().join('/')} às ${bookingState.time}<br>Status: Pendente`}
async function submitBooking(){const btn=$('sendBtn'),sv=db.services.find(s=>s.id===bookingState.service);if(!sv)return;btn.disabled=true;$('bookMsg').innerHTML='';const payload={client_type:bookingState.type==='new'?'new':'returning',service_id:sv.id,customer_name:bookingState.name,phone:bookingState.whats,email:bookingState.email||null,service_name:sv.name,start_at:bookingState.start,end_at:bookingState.end,status:'pending',notes:bookingState.notes||null,policy_accepted:true};const {error}=await SB.from('appointments').insert(payload);if(error){btn.disabled=false;const conflict=error.code==='23P01';$('bookMsg').innerHTML=`<div class="notice error">${conflict?'Ops! Esse horário acabou de ser reservado por outra cliente. Escolha outro horário disponível.':'Não foi possível solicitar: '+esc(error.message)}</div>`;if(conflict){step(3);renderSlots()}return}['s1','s2','s3','s4','s5'].forEach(x=>$(x).classList.add('hidden'));$('success').classList.remove('hidden');$('successBox').innerHTML=`<b>${esc(bookingState.name)}</b><br>${esc(sv.name)}<br>${bookingState.date.split('-').reverse().join('/')} às ${bookingState.time}<br>Status: Pendente<br><br><button class=\"btn\" onclick=\"openWhats()\">ENVIAR AGENDAMENTO PELO WHATSAPP</button><p class=\"muted\">O WhatsApp será aberto com a mensagem pronta. Basta tocar em enviar.</p>`;btn.disabled=false}
function openWhats(){
 const n=String(db.settings.phone||'').replace(/\D/g,'');
 if(n.length<10)return alert('Configure o WhatsApp da Claudete no painel administrativo.');
 const sv=db.services.find(s=>s.id===bookingState.service);
 const data=bookingState.date?bookingState.date.split('-').reverse().join('/'):'Data não informada';
 const msg=[
  'Olá, Claudete! Acabei de fazer um agendamento pelo site Claudete Coiffeur.',
  '',
  `Nome: ${bookingState.name||''}`,
  `Serviço: ${sv?.name||'Não informado'}`,
  `Data: ${data}`,
  `Horário: ${bookingState.time||'Não informado'}`,
  'Status: Pendente',
  '',
  'Gostaria de confirmar meu agendamento.'
 ].join('\n');
 window.open(`https://wa.me/${n}?text=${encodeURIComponent(msg)}`,'_blank');
}

async function openAdmin(){$('admin').classList.add('open');const {data}=await SB.auth.getSession();if(data.session&&await currentIsAdmin()){$('loginView').classList.add('hidden');$('dashView').classList.remove('hidden');await loadAdmin();showTab('dash')}else{$('loginView').classList.remove('hidden');$('dashView').classList.add('hidden')}}
function closeAdmin(){$('admin').classList.remove('open')}
async function currentIsAdmin(){const {data,error}=await SB.from('admin_users').select('id').limit(1);return !error&&data&&data.length>0}
async function loginAdmin(){const email=$('adminUser').value.trim(),password=$('adminPass').value;const {error}=await SB.auth.signInWithPassword({email,password});if(error)return alert('E-mail ou senha incorretos.');if(!await currentIsAdmin()){await SB.auth.signOut();return alert('Essa conta não possui permissão de administradora.')} $('loginView').classList.add('hidden');$('dashView').classList.remove('hidden');await loadAdmin();showTab('dash')}
async function logoutAdmin(){await SB.auth.signOut();$('dashView').classList.add('hidden');$('loginView').classList.remove('hidden')}
async function loadAdmin(){const [a,b,s,c,h,n,set,bh]=await Promise.all([SB.from('appointments').select('*').order('start_at'),SB.from('blocked_periods').select('*').order('start_at'),SB.from('services').select('*').order('name'),SB.from('clients').select('*').order('name'),SB.from('hair_gallery').select('*').order('display_order'),SB.from('nail_gallery').select('*').order('display_order'),SB.from('settings').select('*').limit(1).maybeSingle(),SB.from('business_hours').select('*').order('day_of_week')]);if(a.data)db.appointments=a.data.map(appMap);if(b.data)db.blocks=b.data.map(blockMap);if(s.data)db.services=s.data.map(serviceMap);db.clients=c.data||[];if(h.data)db.hair=h.data.map(galleryMap);if(n.data)db.nails=n.data.map(galleryMap);if(bh.data)db.businessHours=bh.data;if(set.data)db.settings={...db.settings,address:set.data.address||'',phone:set.data.whatsapp||'',instagram:set.data.instagram||'',interval:set.data.appointment_interval_minutes||30,settingsId:set.data.id};renderPublic()}
function showTab(t){({dash:renderDash,apps:renderApps,services:renderServices,blocks:renderBlocks,gallery:renderGallery,settings:renderSettings}[t])()}
function renderDash(){let today=new Date().toISOString().slice(0,10),aps=db.appointments;$('adminContent').innerHTML=`<h2>Dashboard</h2><div class=stats><div class=stat><b>${aps.filter(a=>a.start.slice(0,10)==today).length}</b>Hoje</div><div class=stat><b>${aps.filter(a=>a.status==='Pendente').length}</b>Pendentes</div><div class=stat><b>${aps.filter(a=>a.status==='Confirmado').length}</b>Confirmados</div><div class=stat><b>${(db.clients||[]).length}</b>Clientes</div></div><h3>Próximos agendamentos</h3>${appsTable(aps.filter(a=>new Date(a.start)>=new Date()).slice(0,8))}`}
function appsTable(a){return `<table class=table><tr><th>Cliente</th><th>Serviço</th><th>Data</th><th>Status</th><th>Ações</th></tr>${a.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.service)}</td><td>${new Date(x.start).toLocaleString('pt-BR')}</td><td>${x.status}</td><td><button class=tiny onclick="statusApp('${x.id}','Confirmado')">✓</button> <button class=tiny onclick="statusApp('${x.id}','Concluído')">Fim</button> <button class=tiny onclick="statusApp('${x.id}','Cancelado')">×</button></td></tr>`).join('')}</table>`}
function renderApps(){$('adminContent').innerHTML='<h2>Agendamentos</h2>'+appsTable(db.appointments)}
async function statusApp(id,s){const {error}=await SB.from('appointments').update({status:statusDb(s)}).eq('id',id);if(error)return alert(error.message);await loadAdmin();renderApps()}
function renderServices(){$('adminContent').innerHTML=`<h2>Serviços</h2><div class=card><div class=row><input id=sn placeholder="Nome"><input id=sc placeholder="Categoria"></div><div class=row><input id=sd type=number placeholder="Duração em minutos"><input id=sp type=number step=.01 placeholder="Preço"></div><label><input id=spf type=checkbox style="width:auto"> Preço "A partir de"</label><button class=btn onclick=addService()>Adicionar</button></div><div class=grid>${db.services.map(s=>`<div class=card><b>${esc(s.name)}</b><p>${s.duration} min • ${esc(s.priceText)}</p><button class=tiny onclick="toggleService('${s.id}',${!s.active})">${s.active?'Desativar':'Ativar'}</button> <button class=tiny onclick="delService('${s.id}')">Excluir</button></div>`).join('')}</div>`}
async function addService(){if(!$('sn').value||!$('sd').value)return;const {error}=await SB.from('services').insert({name:$('sn').value,category:$('sc').value||'Outros',duration_minutes:+$('sd').value,price:$('sp').value?+$('sp').value:null,price_from:$('spf').checked,active:true});if(error)return alert(error.message);await loadAdmin();renderServices()}
async function toggleService(id,v){const {error}=await SB.from('services').update({active:v}).eq('id',id);if(error)return alert(error.message);await loadAdmin();renderServices()}
async function delService(id){if(!confirm('Excluir este serviço?'))return;const {error}=await SB.from('services').delete().eq('id',id);if(error)return alert(error.message);await loadAdmin();renderServices()}
function renderBlocks(){$('adminContent').innerHTML=`<h2>Bloqueio de horários</h2><div class=card><div class=row><div><label>Início</label><input id=bs type=datetime-local></div><div><label>Fim</label><input id=be type=datetime-local></div></div><label>Motivo</label><input id=br placeholder="Ex.: almoço / feriado"><button class=btn onclick=addBlock()>Bloquear</button></div><div class=grid>${db.blocks.map(b=>`<div class=card><b>${esc(b.reason||b.title||'Bloqueado')}</b><p>${new Date(b.start).toLocaleString('pt-BR')} → ${new Date(b.end).toLocaleString('pt-BR')}</p><button class=tiny onclick="delBlock('${b.id}')">Excluir</button></div>`).join('')}</div>`}
async function addBlock(){if(!$('bs').value||!$('be').value)return;const {error}=await SB.from('blocked_periods').insert({title:$('br').value||'Bloqueado',reason:$('br').value||'Bloqueado',start_at:new Date($('bs').value).toISOString(),end_at:new Date($('be').value).toISOString()});if(error)return alert(error.message);await loadAdmin();renderBlocks()}
async function delBlock(id){const {error}=await SB.from('blocked_periods').delete().eq('id',id);if(error)return alert(error.message);await loadAdmin();renderBlocks()}
function renderGallery(){$('adminContent').innerHTML=`<h2>Galerias</h2><div class=card><label>Galeria</label><select id=gt><option value=hair>Cabelos</option><option value=nails>Unhas</option></select><label>Título</label><input id=gtitle><label>Categoria</label><input id=gcat><label>Descrição</label><textarea id=gdesc></textarea><label>Imagem</label><input id=gfile type=file accept="image/*"><button class=btn onclick=addGallery()>Adicionar imagem</button><p class=muted>As fotos são enviadas para o Supabase Storage.</p></div><h3>Cabelos</h3><div class="grid gallery">${galleryAdmin(db.hair,'hair')}</div><h3>Unhas</h3><div class="grid gallery">${galleryAdmin(db.nails,'nails')}</div>`}
function galleryAdmin(a,type){return a.map(x=>`<div class=card><img src="${esc(x.img)}"><h3>${esc(x.title)}</h3><button class=tiny onclick="delGallery('${type}','${x.id}','${encodeURIComponent(x.storage_path||'')}')">Excluir</button></div>`).join('')}
async function addGallery(){const f=$('gfile').files[0];if(!f||!$('gtitle').value)return alert('Escolha uma imagem e informe o título.');const type=$('gt').value,folder=type==='hair'?'hair':'nails',path=`${folder}/${Date.now()}-${f.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;let up=await SB.storage.from('gallery').upload(path,f,{upsert:false});if(up.error)return alert(up.error.message);const {data:urlData}=SB.storage.from('gallery').getPublicUrl(path);const table=type==='hair'?'hair_gallery':'nail_gallery';const {error}=await SB.from(table).insert({title:$('gtitle').value,category:$('gcat').value||'Outros',description:$('gdesc').value||null,image_url:urlData.publicUrl,active:true});if(error){await SB.storage.from('gallery').remove([path]);return alert(error.message)}await loadAdmin();renderGallery()}
async function delGallery(type,id){if(!confirm('Excluir esta publicação?'))return;const table=type==='hair'?'hair_gallery':'nail_gallery';const item=(type==='hair'?db.hair:db.nails).find(x=>x.id===id);const {error}=await SB.from(table).delete().eq('id',id);if(error)return alert(error.message);if(item?.image_url){const marker='/storage/v1/object/public/gallery/';const pos=item.image_url.indexOf(marker);if(pos>=0)await SB.storage.from('gallery').remove([decodeURIComponent(item.image_url.slice(pos+marker.length))])}await loadAdmin();renderGallery()}
function renderSettings(){let s=db.settings;$('adminContent').innerHTML=`<h2>Configurações</h2><div class=card><label>Endereço</label><input id=setAddr value="${esc(s.address)}"><label>WhatsApp</label><input id=setPhone value="${esc(s.phone)}"><label>Instagram</label><input id=setInsta value="${esc(s.instagram)}"><label>Intervalo entre opções (min)</label><input id=setInt type=number value="${s.interval}"><button class=btn onclick=saveSettings()>Salvar</button><p class=muted>Horários de abertura/fechamento podem ser alterados diretamente na tabela business_hours do Supabase nesta versão.</p><button class="btn alt" onclick=logoutAdmin()>Sair da conta</button></div>`}
async function saveSettings(){const payload={address:$('setAddr').value,whatsapp:$('setPhone').value,instagram:$('setInsta').value,appointment_interval_minutes:+$('setInt').value};const {error}=await SB.from('settings').update(payload).eq('id',db.settings.settingsId);if(error)return alert(error.message);await loadAdmin();alert('Configurações salvas.')}

loadPublic().catch(e=>{console.error(e);$('servicesGrid').innerHTML='<div class="notice error">Não foi possível conectar ao Supabase. Confira config.js.</div>'});
